/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e5e2e1",
        "error": "#ffb4ab",
        "surface-bright": "#393939",
        "on-background": "#e5e2e1",
        "surface-variant": "#353535",
        "surface-tint": "#c6c6c7",
        "outline": "#8e9192",
        "primary-container": "#e2e2e2",
        "on-primary-container": "#636565",
        "primary-fixed-dim": "#c6c6c7",
        "on-surface-variant": "#c4c7c8",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#1a1c1c",
        "error-container": "#93000a",
        "on-tertiary": "#2f3131",
        "secondary": "#c9c6c5",
        "on-primary": "#2f3131",
        "outline-variant": "#444748",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary-fixed": "#1a1c1c",
        "on-error-container": "#ffdad6",
        "on-secondary": "#313030",
        "tertiary": "#ffffff",
        "primary-fixed": "#e2e2e2",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "surface-container-lowest": "#0e0e0e",
        "surface-container": "#20201f",
        "on-secondary-container": "#b7b4b4",
        "inverse-on-surface": "#313030",
        "primary": "#ffffff",
        "tertiary-fixed-dim": "#c7c6c6",
        "secondary-fixed-dim": "#c9c6c5",
        "on-secondary-fixed-variant": "#474646",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-fixed-variant": "#464747",
        "surface-container-high": "#2a2a2a",
        "background": "#131313",
        "tertiary-container": "#e3e2e2",
        "tertiary-fixed": "#e3e2e2",
        "on-primary-fixed-variant": "#454747",
        "surface": "#131313",
        "surface-container-highest": "#353535",
        "secondary-container": "#474646",
        "on-tertiary-container": "#646464",
        "inverse-primary": "#5d5f5f",
        "inverse-surface": "#e5e2e1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "48px",
        "stack-md": "24px",
        "stack-xs": "4px",
        "stack-sm": "12px",
        "container-max": "1200px",
        "stack-xl": "80px",
        "margin-page": "64px",
        "gutter": "24px",
        "unit": "8px"
      },
      fontFamily: {
        "body-lg": ["Manrope"],
        "display": ["Manrope"],
        "h2": ["Manrope"],
        "h1": ["Manrope"],
        "label-sm": ["Manrope"],
        "body-md": ["Manrope"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "h2": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h1": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
